# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Lucas Nielsen
description: Some general social links for Lucas Nielsen
baseurl: ""
url: https://www.lucasnielsen.com

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Lucas Nielsen
  description:
    - Software Developer
    - Student
    - Really cool guy
  contact:
    phone: +1 605 475 6968
    email: contact@lucasnielsen.com
  
  profiles:
    github: https://github.com/lucasnielsen
    stackoverflow: https://stackoverflow.com/users/22304907/lucas
    linkedin: https://www.linkedin.com/in/lucas-nielsen-5097721b1/
    twitter: https://twitter.com/lucasiscoding
    discord: https://discord.gg/SQPzzduszE

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
