# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Zack (Apraxed)
description: Some general social links for Apraxed
baseurl: ""
url: https://www.apraxed.com

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Zack P
  description:
    - Stupid idiot
    - Student
    - Really cool guy
  contact:
    phone: +1 510 269 7312‬
    email: zack@apraxed.com
  
  profiles:
    github: https://github.com/apraxed
    twitter: https://twitter.com/aprax3d
    discord: https://discord.gg/dqEp6a4WcY

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
